#!/bin/bash
# Coinvestopedia — Prerender Setup Script
# Run from your project root directory

echo "📦 Installing vite-plugin-prerender..."
npm install vite-plugin-prerender --save-dev

echo ""
echo "✅ Installation complete."
echo ""
echo "─── NEXT STEPS ───────────────────────────────────────"
echo ""
echo "1. Replace your vite.config.ts with the provided version"
echo ""
echo "2. Copy these files into your src/ directory:"
echo "   src/hooks/useIsPrerendering.ts"
echo "   src/components/PrerenderFallbacks.tsx"
echo ""
echo "3. Add two lines to each page component:"
echo ""
echo "   import { useIsPrerendering } from '@/hooks/useIsPrerendering'"
echo "   import { HomeStatic } from '@/components/PrerenderFallbacks'"
echo ""
echo "   const isPrerendering = useIsPrerendering()"
echo "   if (isPrerendering) return <HomeStatic />"
echo ""
echo "4. Replace public/robots.txt with the provided version"
echo "   Then in Cloudflare: Security → Bots → Managed robots.txt → OFF"
echo ""
echo "5. Run a test build:"
echo "   npm run build"
echo ""
echo "6. Check dist/ folder — you should see:"
echo "   dist/index.html           ← Home prerendered"
echo "   dist/exchanges/index.html ← Exchanges prerendered"
echo "   dist/macro-intel/index.html"
echo "   dist/tools/index.html"
echo "   dist/knowledge/index.html"
echo "   dist/the-briefing/index.html"
echo "   dist/whale-tracker/index.html"
echo "   dist/asset-comparison/index.html"
echo ""
echo "7. Push to GitHub → Cloudflare Pages auto-deploys"
echo ""
echo "─── VERIFY AFTER DEPLOYMENT ──────────────────────────"
echo ""
echo "Run this curl to confirm crawlers see real HTML:"
echo ""
echo "  curl -A 'GPTBot' https://www.coinvestopedia.com/exchanges"
echo ""
echo "You should see your exchange content in the response,"
echo "NOT an empty <div id='root'></div>"
echo ""
echo "─────────────────────────────────────────────────────"
